packages:
  - packages/*

catalog:
  '@changesets/cli': ^2.29.8
  '@commitlint/cli': ^20.4.1
  '@commitlint/config-conventional': ^20.4.1
  '@types/express': ^5.0.6
  '@types/jest': ^30.0.0
  '@types/node': ^25.2.3
  '@types/supertest': ^6.0.3
  '@nestjs/common': ^11.1.13
  '@nestjs/core': ^11.1.13
  '@nestjs/platform-express': ^11.1.13
  '@nestjs/testing': ^11.1.13
  '@swc/core': ^1.13.5
  '@swc/jest': ^0.2.39
  '@typescript-eslint/eslint-plugin': ^8.55.0
  '@typescript-eslint/parser': ^8.55.0
  eslint: ^9.39.2
  eslint-config-prettier: ^10.1.8
  husky: ^9.1.7
  jest: ^30.2.0
  lint-staged: ^16.2.7
  nyc: ^15.1.0
  prettier: ^3.8.1
  rimraf: ^6.1.3
  rxjs: ^7.8.2
  supertest: ^7.2.2
  turbo: ^2.8.9
  ts-node: ^10.9.2
  typescript: ^5.9.3

ignoredBuiltDependencies:
  - '@nestjs/core'

onlyBuiltDependencies:
  - '@swc/core'
  - unrs-resolver
