name: Feature Request
description: Suggest a new feature or improvement.
title: '[Feature]: '
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement!
        Please describe your idea so we can evaluate and discuss it.

  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package does this relate to?
      options:
        - '@miinded/nestjs-s3'
        - '@miinded/nestjs-google-drive'
        - Both / monorepo-wide
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem are you trying to solve? What limitation are you hitting?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the solution or API you would like to see.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions or workarounds you have considered.
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other information, code samples, or references that support this request.
    validations:
      required: false
